---
# handlers file for elasticsearch
- name: Reload systemd daemon
  ansible.builtin.systemd_service:
    daemon_reload: yes
    
- name: Restart Elasticsearch
  service:
    name: elasticsearch
    state: restarted
